# Generated by Django 3.2.4 on 2021-07-06 15:40

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20210706_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recruiter', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=70)),
                ('town_or_city', models.CharField(max_length=70)),
                ('postcode', models.CharField(max_length=70)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_creator', models.BooleanField(default=False)),
            ],
        ),
    ]
