# Generated by Django 3.2.4 on 2021-07-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210706_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='is_recruiter',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
