# Generated by Django 3.2.4 on 2021-07-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210707_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
