# Generated by Django 3.2.4 on 2021-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_category_creator_creatorwork_education_languages_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorwork',
            name='skills',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
