# Generated by Django 3.2.4 on 2021-07-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_creatorwork_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Web, Mobile & Software Dev', (('DESKTOP', 'Desktop Software Development'), ('MOBILE', 'Mobile Development'), ('GAME', 'Game Development'), ('OTHER', 'Other Software Development'), ('TESTING', 'Testing'), ('UX', 'Web UX & Mobile Design'), ('WEB', 'Web Development'))), ('Design & Creative', (('ART', 'Art & Illustration'), ('AUDIO', 'Audio & Music Production'), ('VIDEO', 'Video & Animation'), ('DESIGN', 'Graphic, Editorial & Presentation Design'), ('ARTS', 'Performing Arts'), ('PHOTO', 'Photography'), ('BRANDING', 'Branding & Logo Design'), ('GAMING', 'Gaming AR/VR'))), ('Writing', (('CONTENT', 'Content & Copyright'), ('CREATIVE', 'Creative'), ('EDITING', 'Editing & Proofreading'), ('RESUMES', 'Resumes & Cover Letters'), ('TECHNICAL', 'Technical Writing'))), ('Translation', (('GENERAL', 'General'), ('LEGAL', 'Legal'), ('MEDICAL', 'Medical'), ('TECHNICAL', 'Technical')))], default='DE', max_length=70),
        ),
    ]
