# Generated by Django 3.2.4 on 2021-07-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_category_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorwork',
            name='category',
        ),
    ]
