# Generated by Django 3.2.4 on 2021-08-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210810_2256'),
        ('profiles', '0012_auto_20210719_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorwork',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatorwork',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.subcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
