# Generated by Django 3.2.4 on 2021-07-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Web, Mobile & Software Dev', (('DESKTOP', 'Desktop Software Development'), ('MOBILE', 'Mobile Development'), ('GAME', 'Game Development'), ('OTHER', 'Other Software Development'), ('TESTING', 'Testing'), ('UX', 'Web UX & Mobile Design'), ('WEB', 'Web Development'))), ('Design & Creative', (('ART', 'Art & Illustration'), ('AUDIO', 'Audio & Music Production'), ('VIDEO', 'Video & Animation'), ('DESIGN', 'Graphic, Editorial & Presentation Design'), ('ARTS', 'Performing Arts'), ('PHOTO', 'Photography'), ('BRANDING', 'Branding & Logo Design'), ('GAMING', 'Gaming AR/VR'))), ('Writing', (('CONTENT', 'Content & Copyright'), ('CREATIVE', 'Creative'), ('EDITING', 'Editing & Proofreading'), ('RESUMES', 'Resumes & Cover Letters'), ('TECHNICAL', 'Technical Writing'))), ('Translation', (('GENERAL', 'General'), ('LEGAL', 'Legal'), ('MEDICAL', 'Medical'), ('TECHNICAL', 'Technical')))], max_length=80)),
                ('service_headline', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
                ('service_search_tags', models.CharField(blank=True, max_length=120, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('faq_question', models.CharField(blank=True, max_length=120, null=True)),
                ('faq_answer', models.TextField(blank=True, null=True)),
                ('enable_all_packages', models.BooleanField(default=True)),
                ('basic_package_title', models.CharField(max_length=50)),
                ('basic_delivery_time', models.IntegerField(choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')])),
                ('basic_revisions', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')])),
                ('basic_details', models.TextField()),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('standard_package_title', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_delivery_time', models.IntegerField(blank=True, choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')], null=True)),
                ('standard_revisions', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], null=True)),
                ('standard_details', models.TextField(blank=True, null=True)),
                ('standard_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('premium_package_title', models.CharField(blank=True, max_length=50, null=True)),
                ('premium_delivery_time', models.IntegerField(blank=True, choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')], null=True)),
                ('premium_revisions', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], null=True)),
                ('premium_details', models.TextField(blank=True, null=True)),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Freelance Services',
            },
        ),
    ]
