# Generated by Django 3.2.4 on 2021-07-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelanceservice',
            options={'verbose_name_plural': 'Freelance Services'},
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='faq_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='faq_question',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='premium_delivery_time',
            field=models.IntegerField(blank=True, choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')], null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='premium_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='premium_package_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='premium_revisions',
            field=models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='standard_delivery_time',
            field=models.IntegerField(blank=True, choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')], null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='standard_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='standard_package_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='standard_revisions',
            field=models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], null=True),
        ),
    ]
