# Generated by Django 3.2.4 on 2021-07-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210720_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelanceservice',
            name='service_subcategory',
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='service_category',
            field=models.CharField(choices=[], max_length=80),
        ),
    ]
