# Generated by Django 3.2.4 on 2021-08-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_freelanceservice_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='basic_package_title',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='premium_package_title',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='service_headline',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='freelanceservice',
            name='standard_package_title',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
    ]
