# Generated by Django 3.2.4 on 2021-08-07 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_auto_20210807_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=90)),
                ('package_description', models.TextField()),
                ('client_requirements', models.TextField(blank=True, null=True)),
                ('delivery_time', models.IntegerField(choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')])),
                ('revisions', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')])),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fast_delivery_time', models.IntegerField(blank=True, choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')], null=True)),
                ('fast_delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reference_images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=90)),
                ('package_description', models.TextField()),
                ('client_requirements', models.TextField(blank=True, null=True)),
                ('delivery_time', models.IntegerField(choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')])),
                ('revisions', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')])),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fast_delivery_time', models.IntegerField(blank=True, choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')], null=True)),
                ('fast_delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reference_images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StandardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=90)),
                ('package_description', models.TextField()),
                ('client_requirements', models.TextField(blank=True, null=True)),
                ('delivery_time', models.IntegerField(choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')])),
                ('revisions', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')])),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fast_delivery_time', models.IntegerField(blank=True, choices=[(1, 'One Day'), (2, 'Two Day'), (3, 'Three Day'), (4, 'Four Day'), (5, 'Five Day'), (6, 'Six Day'), (7, 'Seven Day'), (12, 'Twelve Day'), (14, 'Two Week'), (21, 'Three Week'), (30, 'One Month')], null=True)),
                ('fast_delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reference_images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=90)),
                ('description', models.TextField()),
                ('search_tags', models.CharField(blank=True, max_length=120, null=True)),
                ('images', models.ImageField(upload_to='')),
                ('faq_question_1', models.CharField(blank=True, max_length=120, null=True)),
                ('faq_answer_1', models.TextField(blank=True, null=True)),
                ('faq_question_2', models.CharField(blank=True, max_length=120, null=True)),
                ('faq_answer_2', models.TextField(blank=True, null=True)),
                ('faq_question_3', models.CharField(blank=True, max_length=120, null=True)),
                ('faq_answer_3', models.TextField(blank=True, null=True)),
                ('faq_question_4', models.CharField(blank=True, max_length=120, null=True)),
                ('faq_answer_4', models.TextField(blank=True, null=True)),
                ('enable_all_packages', models.BooleanField(default=True)),
                ('include_client_requirements', models.BooleanField(default=False)),
                ('requirements_same_for_all', models.BooleanField(default=True)),
                ('shipping_required', models.BooleanField(default=False)),
                ('enable_fast_delivery', models.BooleanField(default=True)),
                ('enable_extra_revisions', models.BooleanField(default=True)),
                ('extra_revisions', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')])),
                ('extra_revision_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('basic_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.basicpackage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
                ('premium_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.premiumpackage')),
                ('standard_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.standardpackage')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
