# Generated by Django 3.2.4 on 2021-08-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_basicpackage_premiumpackage_service_standardpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='basic_package',
        ),
        migrations.RemoveField(
            model_name='service',
            name='enable_extra_revisions',
        ),
        migrations.RemoveField(
            model_name='service',
            name='enable_fast_delivery',
        ),
        migrations.RemoveField(
            model_name='service',
            name='extra_revision_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='extra_revisions',
        ),
        migrations.RemoveField(
            model_name='service',
            name='premium_package',
        ),
        migrations.RemoveField(
            model_name='service',
            name='standard_package',
        ),
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
