# Generated by Django 3.2.4 on 2021-07-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_freelanceservice_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelanceservice',
            old_name='service_category',
            new_name='category_name',
        ),
    ]
