# Generated by Django 3.2.4 on 2021-08-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210808_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpackage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='standardpackage',
            name='id',
        ),
        migrations.AddField(
            model_name='basicpackage',
            name='service',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='service',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardpackage',
            name='service',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.service'),
            preserve_default=False,
        ),
    ]
