# Generated by Django 3.2.4 on 2021-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210808_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='enable_all_packages',
        ),
        migrations.AddField(
            model_name='basicpackage',
            name='enable_all_packages',
            field=models.BooleanField(default=True),
        ),
    ]
