# Generated by Django 3.2.4 on 2021-08-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210810_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_client_requirements',
            new_name='client_requirements',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_delivery_time',
            new_name='delivery_time',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_fast_delivery_price',
            new_name='fast_delivery_price',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_fast_delivery_time',
            new_name='fast_delivery_time',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_package_description',
            new_name='package_description',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_package_title',
            new_name='package_title',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_reference_images',
            new_name='reference_images',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='premium_revisions',
            new_name='revisions',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_client_requirements',
            new_name='client_requirements',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_delivery_time',
            new_name='delivery_time',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_fast_delivery_price',
            new_name='fast_delivery_price',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_fast_delivery_time',
            new_name='fast_delivery_time',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_package_description',
            new_name='package_description',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_package_title',
            new_name='package_title',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_reference_images',
            new_name='reference_images',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='standard_revisions',
            new_name='revisions',
        ),
    ]
