# Generated by Django 3.2.4 on 2021-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210626_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2021-07-02', verbose_name='date of birth'),
        ),
    ]
