# Generated by Django 3.2.4 on 2021-07-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210706_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2021-07-18', verbose_name='date of birth'),
        ),
    ]
