# Generated by Django 3.2.4 on 2021-08-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210810_2256'),
        ('checkout', '0003_auto_20210812_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='services.basicpackage'),
        ),
        migrations.DeleteModel(
            name='OrderPackage',
        ),
    ]
