# Generated by Django 3.2.4 on 2021-08-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderlineitem_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
            preserve_default=False,
        ),
    ]
