# Generated by Django 3.2.4 on 2021-08-13 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='service_price',
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
