# Generated by Django 3.2.4 on 2021-08-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210813_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
