# Generated by Django 3.2.4 on 2021-08-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210813_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='order_subtotal',
        ),
    ]
